using System;
namespace Retorno_Debito_Automatico.Layouts
{
	internal class Cod_Retorno_Banco
	{
		public string[] descricao = new string[]
		{
			"00DEBITO EFETUADO",
			"01DEBITO NAO EFETUADO - INSUFICIENCIA DE FUNDOS",
			"02DEBITO NAO EFETUADO - CONTA NAO CADASTRADA",
			"04DEBITO NAO EFETUADO - OUTRAS RESTRICOES",
			"05DEBITO NAO EFETUADO – VALOR DO DEBITO EXCEDE VALOR LIMITE APROVADO",
			"10DEBITO NAO EFETUADO - AGENCIA EM REGIME DE ENCERRAMENTO",
			"12DEBITO NAO EFETUADO - VALOR INVALIDO",
			"13DEBITO NAO EFETUADO - DATA DE LANCAMENTO INVALIDA",
			"14DEBITO NAO EFETUADO - AGENCIA INVALIDA",
			"15DEBITO NAO EFETUADO - CONTA INVALIDA",
			"18DEBITO NAO EFETUADO - DATA DO DEBITO ANTERIOR A DO PROCESSAMENTO",
			"19DEBITO NAO EFETUADO – AGENCIA/CONTA NAO PERTENCE AO CPF/CNPJ INFORMADO",
			"20DEBITO NAO EFETUADO – CONTA CONJUNTA NAO SOLIDARIA",
			"30DEBITO NAO EFETUADO - SEM CONTRATO DE DEBUTI AUTOMATICO",
			"31DEBITO EFETUADO EM DATA DIFERENTE DA DATA INFORMADA – FERIADO NA PRACA DE DEBITO",
			"96MANUTENCAO DO CADASTRO",
			"97CANCELAMENTO - NAO ENCONTRADO",
			"98CANCELAMENTO - NAO EFETUADO, FORA DO TEMPO HABIL",
			"99CANCELAMENTO - CANCELADO CONFORME SOLICITACAO"
		};
	}
}
